version: '3.9'
 
services:
  redis1:
    image: redis:7.2
    container_name: redis1
    ports:
      - "6379:6379"    # external client access
      - "16379:16379"  # internal cluster bus
    volumes:
      - ./redis1/data:/data
      - ./redis1/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
 
  redis2:
    image: redis:7.2
    container_name: redis2
    ports:
      - "6380:6379"
      - "16380:16379"
    volumes:
      - ./redis2/data:/data
      - ./redis2/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
 
  redis3:
    image: redis:7.2
    container_name: redis3
    ports:
      - "6381:6379"
      - "16381:16379"
    volumes:
      - ./redis3/data:/data
      - ./redis3/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]